name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - name: Build binaries
        run: |
          # Build for multiple platforms using build.sh
          GOOS=linux GOARCH=amd64 ./build.sh
          GOOS=linux GOARCH=arm64 ./build.sh
          GOOS=darwin GOARCH=amd64 ./build.sh
          GOOS=darwin GOARCH=arm64 ./build.sh
          
      - name: Create checksums
        run: |
          cd build
          sha256sum * > checksums.txt
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/opwriting-linux-amd64
            build/opwriting-linux-arm64
            build/opwriting-darwin-amd64
            build/opwriting-darwin-arm64
            build/checksums.txt
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}